markdown: rdiscount
permalink: /:title/
url: http://yonsm.net
name: '凝思集'
author: zwq00000
qq: zwq00000@sohu.com
email: zwq00000@gmail.com 
duoshuo: zwq00000
beian: ''
cnzz: 119959
weibo: ''
github: zwq00000
pygments: true
safe: true
paginate: 20
about: "这里是 赵卫强 的个人博客，创建于 2013 年。开始使用了 ExBlog 博客程序；之后长期（2004 ~ 2011）使用 Bo-Blog；2012 年更换为 WordProess；2003年7月迁移到 Jekyll @ GitHub。<br /><br />这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
